parser: babel-eslint
env:
  browser: true
  jest: true
  jest/globals: true
plugins:
  - import
  - jest
  - prettier
rules:
  prettier/prettier: error
extends:
  - airbnb/base
  - plugin:jest/recommended
  - prettier
